//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://wsdl.epuap.gov.pl/obiekty/", ClrNamespace="wsdl.epuap.gov.pl.obiekty")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//KD dodałem zapis w tej lini, żeby był tylko podpis
//[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.epuap.gov.pl/pull/", ConfigurationName="pull") ]
  [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.epuap.gov.pl/pull/", ConfigurationName="PullService.pull", ProtectionLevel = System.Net.Security.ProtectionLevel.Sign) ]
  
  
public interface pull
{
    
    // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ operacja „oczekujaceDokumenty” nie jest ani wywołaniem RPC, ani opakowanym dokumentem.
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(wsdl.epuap.gov.pl.obiekty.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
    oczekujaceDokumentyResponse oczekujaceDokumenty(oczekujaceDokumentyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", ReplyAction="*")]
    System.Threading.Tasks.Task<oczekujaceDokumentyResponse> oczekujaceDokumentyAsync(oczekujaceDokumentyRequest request);
    
    // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ operacja „pobierzNastepny” nie jest ani wywołaniem RPC, ani opakowanym dokumentem.
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/pobierzNastepny", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(wsdl.epuap.gov.pl.obiekty.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/pobierzNastepny", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
    pobierzNastepnyResponse pobierzNastepny(pobierzNastepnyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/pobierzNastepny", ReplyAction="*")]
    System.Threading.Tasks.Task<pobierzNastepnyResponse> pobierzNastepnyAsync(pobierzNastepnyRequest request);
    
    // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ operacja „potwierdzOdebranie” nie jest ani wywołaniem RPC, ani opakowanym dokumentem.
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/potwierdzOdebranie", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(wsdl.epuap.gov.pl.obiekty.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/potwierdzOdebranie", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
    potwierdzOdebranieResponse potwierdzOdebranie(potwierdzOdebranieRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/potwierdzOdebranie", ReplyAction="*")]
    System.Threading.Tasks.Task<potwierdzOdebranieResponse> potwierdzOdebranieAsync(potwierdzOdebranieRequest request);
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullOczekujaceTyp : ZapytaniePullTyp
{
}

/// <uwagi/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPotwierdzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPobierzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullOczekujaceTyp))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullTyp
{
    
    private string podmiotField;
    
    private string nazwaSkrytkiField;
    
    private string adresSkrytkiField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string podmiot
    {
        get
        {
            return this.podmiotField;
        }
        set
        {
            this.podmiotField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string nazwaSkrytki
    {
        get
        {
            return this.nazwaSkrytkiField;
        }
        set
        {
            this.nazwaSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string adresSkrytki
    {
        get
        {
            return this.adresSkrytkiField;
        }
        set
        {
            this.adresSkrytkiField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DokumentTyp
{
    
    private string nazwaPlikuField;
    
    private string typPlikuField;
    
    private byte[] zawartoscField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string nazwaPliku
    {
        get
        {
            return this.nazwaPlikuField;
        }
        set
        {
            this.nazwaPlikuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string typPliku
    {
        get
        {
            return this.typPlikuField;
        }
        set
        {
            this.typPlikuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
    public byte[] zawartosc
    {
        get
        {
            return this.zawartoscField;
        }
        set
        {
            this.zawartoscField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DaneNadawcyTyp
{
    
    private string uzytkownikField;
    
    private string systemField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string uzytkownik
    {
        get
        {
            return this.uzytkownikField;
        }
        set
        {
            this.uzytkownikField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string system
    {
        get
        {
            return this.systemField;
        }
        set
        {
            this.systemField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class DanePodmiotuTyp
{
    
    private string identyfikatorField;
    
    private string typOsobyField;
    
    private string imieSkrotField;
    
    private string nazwiskoNazwaField;
    
    private string nipField;
    
    private string peselField;
    
    private string regonField;
    
    private bool zgodaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string identyfikator
    {
        get
        {
            return this.identyfikatorField;
        }
        set
        {
            this.identyfikatorField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string typOsoby
    {
        get
        {
            return this.typOsobyField;
        }
        set
        {
            this.typOsobyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string imieSkrot
    {
        get
        {
            return this.imieSkrotField;
        }
        set
        {
            this.imieSkrotField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string nazwiskoNazwa
    {
        get
        {
            return this.nazwiskoNazwaField;
        }
        set
        {
            this.nazwiskoNazwaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string nip
    {
        get
        {
            return this.nipField;
        }
        set
        {
            this.nipField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string pesel
    {
        get
        {
            return this.peselField;
        }
        set
        {
            this.peselField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string regon
    {
        get
        {
            return this.regonField;
        }
        set
        {
            this.regonField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public bool zgoda
    {
        get
        {
            return this.zgodaField;
        }
        set
        {
            this.zgodaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class StatusTyp
{
    
    private int kodField;
    
    private string komunikatField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int kod
    {
        get
        {
            return this.kodField;
        }
        set
        {
            this.kodField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
    public string komunikat
    {
        get
        {
            return this.komunikatField;
        }
        set
        {
            this.komunikatField = value;
        }
    }
}

/// <uwagi/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPotwierdzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPobierzTyp))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullOczekujaceTyp))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullTyp
{
    
    private StatusTyp statusField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public StatusTyp status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullPotwierdzTyp : OdpowiedzPullTyp
{
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullPobierzTyp : OdpowiedzPullTyp
{
    
    private DanePodmiotuTyp danePodmiotuField;
    
    private DaneNadawcyTyp daneNadawcyField;
    
    private System.DateTime dataNadaniaField;
    
    private string nazwaSkrytkiField;
    
    private string adresSkrytkiField;
    
    private string adresOdpowiedziField;
    
    private bool czyTestoweField;
    
    private byte[] daneDodatkoweField;
    
    private DokumentTyp dokumentField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public DanePodmiotuTyp danePodmiotu
    {
        get
        {
            return this.danePodmiotuField;
        }
        set
        {
            this.danePodmiotuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public DaneNadawcyTyp daneNadawcy
    {
        get
        {
            return this.daneNadawcyField;
        }
        set
        {
            this.daneNadawcyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public System.DateTime dataNadania
    {
        get
        {
            return this.dataNadaniaField;
        }
        set
        {
            this.dataNadaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string nazwaSkrytki
    {
        get
        {
            return this.nazwaSkrytkiField;
        }
        set
        {
            this.nazwaSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string adresSkrytki
    {
        get
        {
            return this.adresSkrytkiField;
        }
        set
        {
            this.adresSkrytkiField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
    public string adresOdpowiedzi
    {
        get
        {
            return this.adresOdpowiedziField;
        }
        set
        {
            this.adresOdpowiedziField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public bool czyTestowe
    {
        get
        {
            return this.czyTestoweField;
        }
        set
        {
            this.czyTestoweField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
    public byte[] daneDodatkowe
    {
        get
        {
            return this.daneDodatkoweField;
        }
        set
        {
            this.daneDodatkoweField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public DokumentTyp dokument
    {
        get
        {
            return this.dokumentField;
        }
        set
        {
            this.dokumentField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class OdpowiedzPullOczekujaceTyp : OdpowiedzPullTyp
{
    
    private int oczekujaceField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int oczekujace
    {
        get
        {
            return this.oczekujaceField;
        }
        set
        {
            this.oczekujaceField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullPotwierdzTyp : ZapytaniePullTyp
{
    
    private string skrotField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string skrot
    {
        get
        {
            return this.skrotField;
        }
        set
        {
            this.skrotField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
public partial class ZapytaniePullPobierzTyp : ZapytaniePullTyp
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class oczekujaceDokumentyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace;
    
    public oczekujaceDokumentyRequest()
    {
    }
    
    public oczekujaceDokumentyRequest(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace)
    {
        this.ZapytaniePullOczekujace = ZapytaniePullOczekujace;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class oczekujaceDokumentyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public OdpowiedzPullOczekujaceTyp OdpowiedzPullOczekujace;
    
    public oczekujaceDokumentyResponse()
    {
    }
    
    public oczekujaceDokumentyResponse(OdpowiedzPullOczekujaceTyp OdpowiedzPullOczekujace)
    {
        this.OdpowiedzPullOczekujace = OdpowiedzPullOczekujace;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pobierzNastepnyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public ZapytaniePullPobierzTyp ZapytaniePullPobierz;
    
    public pobierzNastepnyRequest()
    {
    }
    
    public pobierzNastepnyRequest(ZapytaniePullPobierzTyp ZapytaniePullPobierz)
    {
        this.ZapytaniePullPobierz = ZapytaniePullPobierz;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pobierzNastepnyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public OdpowiedzPullPobierzTyp OdpowiedzPullPobierz;
    
    public pobierzNastepnyResponse()
    {
    }
    
    public pobierzNastepnyResponse(OdpowiedzPullPobierzTyp OdpowiedzPullPobierz)
    {
        this.OdpowiedzPullPobierz = OdpowiedzPullPobierz;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class potwierdzOdebranieRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz;
    
    public potwierdzOdebranieRequest()
    {
    }
    
    public potwierdzOdebranieRequest(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz)
    {
        this.ZapytaniePullPotwierdz = ZapytaniePullPotwierdz;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class potwierdzOdebranieResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
    public OdpowiedzPullPotwierdzTyp OdpowiedzPullPotwierdz;
    
    public potwierdzOdebranieResponse()
    {
    }
    
    public potwierdzOdebranieResponse(OdpowiedzPullPotwierdzTyp OdpowiedzPullPotwierdz)
    {
        this.OdpowiedzPullPotwierdz = OdpowiedzPullPotwierdz;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface pullChannel : pull, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class pullClient : System.ServiceModel.ClientBase<pull>, pull
{
    
    public pullClient()
    {
    }
    
    public pullClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public pullClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public pullClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public pullClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    oczekujaceDokumentyResponse pull.oczekujaceDokumenty(oczekujaceDokumentyRequest request)
    {
        return base.Channel.oczekujaceDokumenty(request);
    }
    
    public OdpowiedzPullOczekujaceTyp oczekujaceDokumenty(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace)
    {
        oczekujaceDokumentyRequest inValue = new oczekujaceDokumentyRequest();
        inValue.ZapytaniePullOczekujace = ZapytaniePullOczekujace;
        oczekujaceDokumentyResponse retVal = ((pull)(this)).oczekujaceDokumenty(inValue);
        return retVal.OdpowiedzPullOczekujace;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<oczekujaceDokumentyResponse> pull.oczekujaceDokumentyAsync(oczekujaceDokumentyRequest request)
    {
        return base.Channel.oczekujaceDokumentyAsync(request);
    }
    
    public System.Threading.Tasks.Task<oczekujaceDokumentyResponse> oczekujaceDokumentyAsync(ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace)
    {
        oczekujaceDokumentyRequest inValue = new oczekujaceDokumentyRequest();
        inValue.ZapytaniePullOczekujace = ZapytaniePullOczekujace;
        return ((pull)(this)).oczekujaceDokumentyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    pobierzNastepnyResponse pull.pobierzNastepny(pobierzNastepnyRequest request)
    {
        return base.Channel.pobierzNastepny(request);
    }
    
    public OdpowiedzPullPobierzTyp pobierzNastepny(ZapytaniePullPobierzTyp ZapytaniePullPobierz)
    {
        pobierzNastepnyRequest inValue = new pobierzNastepnyRequest();
        inValue.ZapytaniePullPobierz = ZapytaniePullPobierz;
        pobierzNastepnyResponse retVal = ((pull)(this)).pobierzNastepny(inValue);
        return retVal.OdpowiedzPullPobierz;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<pobierzNastepnyResponse> pull.pobierzNastepnyAsync(pobierzNastepnyRequest request)
    {
        return base.Channel.pobierzNastepnyAsync(request);
    }
    
    public System.Threading.Tasks.Task<pobierzNastepnyResponse> pobierzNastepnyAsync(ZapytaniePullPobierzTyp ZapytaniePullPobierz)
    {
        pobierzNastepnyRequest inValue = new pobierzNastepnyRequest();
        inValue.ZapytaniePullPobierz = ZapytaniePullPobierz;
        return ((pull)(this)).pobierzNastepnyAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    potwierdzOdebranieResponse pull.potwierdzOdebranie(potwierdzOdebranieRequest request)
    {
        return base.Channel.potwierdzOdebranie(request);
    }
    
    public OdpowiedzPullPotwierdzTyp potwierdzOdebranie(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz)
    {
        potwierdzOdebranieRequest inValue = new potwierdzOdebranieRequest();
        inValue.ZapytaniePullPotwierdz = ZapytaniePullPotwierdz;
        potwierdzOdebranieResponse retVal = ((pull)(this)).potwierdzOdebranie(inValue);
        return retVal.OdpowiedzPullPotwierdz;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<potwierdzOdebranieResponse> pull.potwierdzOdebranieAsync(potwierdzOdebranieRequest request)
    {
        return base.Channel.potwierdzOdebranieAsync(request);
    }
    
    public System.Threading.Tasks.Task<potwierdzOdebranieResponse> potwierdzOdebranieAsync(ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz)
    {
        potwierdzOdebranieRequest inValue = new potwierdzOdebranieRequest();
        inValue.ZapytaniePullPotwierdz = ZapytaniePullPotwierdz;
        return ((pull)(this)).potwierdzOdebranieAsync(inValue);
    }
}
namespace wsdl.epuap.gov.pl.obiekty
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/", IsNullable=false)]
    public partial class WyjatekTyp : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("WyjatekTyp", "http://wsdl.epuap.gov.pl/obiekty/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
